### PR TITLE
Update dependencies to latest versions

### PR DESCRIPTION
**Pull request by biomorgoth**
These changes only point to update all the dependencies for the project, including any changes for tests to pass.

All these changes were tested on Elixir versions 1.10.3 and 1.10.4.

The only change in tests was to update the `Poison.Encoder.encode` options, as in new version 4.0 it is changed to a Map. The 0.6.0 AWS dependency also manages this change (see https://github.com/aws-beam/aws-elixir/blob/v0.6.0/lib/aws/logs.ex#L624 ) so its the compatible version. Once made, all tests passed with no problem.

Also, `credo` was updated as the previous version did not worked. Now it processes and outputs correctly.

`ex_doc` was updated in order to be compatible with Elixir versions 1.7 or higher. See: https://github.com/elixir-lang/ex_doc#using-exdoc-with-mix . Docs were generated with no problem.

Let me know if there is any consideration for this to be integrated in the codebase, so a new version can be available via Hex.

### CODE REVIEW

**Comment by biomorgoth** [comment]
I can see Travis is failing on build a version for Elixir 1.5 with the following error:
```
warning: the dependency :gettext requires Elixir "~> 1.6" but you are running on v1.5.1
```

Should this be a stopper for having this project dependencies updated? Tests on 1.8.2 reported as success. I can update `.travis.yml` if it is ok to remote 1.5.1 (and add newer versions) from CI builds.

**Comment by lboekhorst** [comment]
Hi @biomorgoth!

Thanks a bunch for the pull request! I was on holiday last week but I will make sure to to review and push a new build to Hex this week.

**Comment by biomorgoth** [comment]
Hello @lboekhorst !

No problem! Just let me know if setting the lowest Elixir version to 1.6 on travis config file suits you fine. And of course any other issue the PR could have.

Greetings.

**Comment by biomorgoth** [comment]
Hi @lboekhorst , let me know if there is anything i can do to help about this PR.

Greetings.

**Comment by felipeloha** [comment]
what is the status of this? 
our project is hanging with an old poison version because cloudwatch does not use the latest aws-elixir.
is there a way to help with this?

**Comment by pmenhart** [comment]
Hi @biomorgoth,
Closing this PR because we took a different approach, with Poison removed. However, I applied your dependency updates - thanks :-)
Hope you'll find the new release useful. Your feedback will be appreciated!
Peter

**Comment by biomorgoth** [comment]
No prob @pmenhart , nice to know that Poison was removed as its version incompatibilities were the reason i had to create this PR at first. I'm glad some other parts of the PR were still valuable for the project.

**Pull request closed without merging**
